"""initial schema

Revision ID: 59c0a5b719e2
Revises:
Create Date: 2026-08-01 21:55:06.966806

Hand-written, not autogenerated: no Postgres server exists in this development environment
(Docker Compose per PLAN.md §17 isn't set up here), and Alembic's --autogenerate diffs
target_metadata against a *live, connected* database — there's nothing to diff against.
PLAN.md §2 itself warns not to rely on autogenerate blindly and to review generated
migrations, so a hand-written migration reviewed against the actual ORM column definitions
(inspected directly from app.auth.models.User / app.models.pipeline_template.PipelineTemplate
/ app.models.execution_log.ExecutionLog before writing this file) is the more careful choice
here, not a shortcut. Verified by actually running upgrade() then downgrade() against a real
SQLite database in tests/test_models.py — not just eyeballed.

Uses the same cross-dialect types as the ORM models (GUID, JSONB-with-SQLite-variant) rather
than raw postgresql.UUID/JSONB — a first attempt using the raw Postgres types failed outright
against SQLite (JSONB has no SQLite compiler at all), which is exactly why: this way the
migration's DDL matches what the ORM models actually declare, and stays testable without a
live Postgres server, while still producing the identical native UUID/JSONB columns in
production (both types are specifically designed to render as Postgres-native under the
postgresql dialect and degrade gracefully elsewhere).

Creates all three tables in FK-dependency order: user -> pipeline_template -> execution_log.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.types import JSON

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59c0a5b719e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_JSON_TYPE = JSONB().with_variant(JSON(), "sqlite")


def upgrade() -> None:
    op.create_table(
        "user",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_superuser", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_user_email", "user", ["email"], unique=True)

    op.create_table(
        "pipeline_template",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("owner_id", GUID(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pipeline_json", _JSON_TYPE, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.func.now(),
            onupdate=sa.func.now(), nullable=False,
        ),
    )

    op.create_table(
        "execution_log",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("template_id", GUID(), sa.ForeignKey("pipeline_template.id"), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("run_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("status IN ('success', 'error')", name="ck_execution_log_status"),
    )


def downgrade() -> None:
    op.drop_table("execution_log")
    op.drop_table("pipeline_template")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_table("user")
